spring:
  application:
    name: fis-training-test-02
  datasource:
    url: jdbc:mysql://localhost:3306/fis_training?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 02221999
  jpa:
    show-sql: true
    generate-ddl: true